services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: buoi5-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "YourStrong@Pass123"
    ports:
      - "1433:1433"
    volumes:
      - buoi5-sql-data:/var/opt/mssql

volumes:
  buoi5-sql-data:
